### ISSUE TITLE
Failed to open the FASTA file effa

### ISSUE THREAD

**Issue by zhangjianruwang** [NCGG-MGC/IMSindel#1]
hello, I got an error when using imsindel to call long deletion.
About the dependencies: I use conda to install MAFFT and fasta3.
for bioruby, I use apt-get install ruby-bio.
the command I use to run imsindel is 
imsindel --chr chr18 --bam PV32_sorted_markdup.bam --outd ./results/ --indelsize 10000 -reffa hg19_bwa.fa  1>chr18_imsindel.log 2>chr18_imsindel.log

reffa( hg19_bwa) can be RWX for all users, and I have produce fai by samtools faidx.

The following lines are error log.

>6. detection of indels...
#paired long indel candidates:	77
#unpaired long indel candidates:	338
#short indel candidates:	4304
[E::fai_build3] Failed to open the FASTA file effa
Could not load fai index of effa
/1/public_resources/softwares/*/IMSindel/lib/ims_indel/indel_detector.rb:91:in `block in detect_indels': undefined method `join' for nil:NilClass (NoMethodError)
	from /1/public_resources/softwares/*/IMSindel/lib/ims_indel/indel_detector.rb:62:in `each'
	from /1/public_resources/softwares/*/IMSindel/lib/ims_indel/indel_detector.rb:62:in `each_with_index'
	from /1/public_resources/softwares/*/IMSindel/lib/ims_indel/indel_detector.rb:62:in `detect_indels'
	from /1/public_resources/softwares/*/IMSindel/lib/ims_indel/indel_detector.rb:15:in `indel_call'
	from /1/public_resources/softwares/*/IMSindel/lib/ims_indel.rb:90:in `run_detect_indels'
	from /1/public_resources/softwares/*/IMSindel/lib/ims_indel.rb:21:in `run'
	from /1/public_resources/softwares/*/IMSindel/bin/imsindel:43:in `<main>'

**Comment by holrock** [comment]
Thank you for using our IMSindel.
The error occurs by missing one hyphen of `reffa` option.
The option is not  `-reffa`, but `--reffa`.

**Comment by zhangjianruwang** [comment]
That was folly.

**Comment by chenatf** [comment]
Thanks for reply. The guy found his mistake after the software ran 10 hours, it is time-consuming to find the  mistake. May you construct a static syntax analysis to quickly report the syntax mistake before the program starts running ?

**Comment by holrock** [comment]
Technically, while `-reffa` is valid syntax, that means  `--reffa effa`.
To avoid this time-consuming, we modify our program to confirm the existence of the file beforehand.

**Comment by holrock** [comment]
fix: 8e3f2ee73a37bce3797f1ddcc702e40a759deba2
