### ISSUE TITLE
What do hyphens mean?

### ISSUE THREAD

**Issue by shig913** [NCGG-MGC/IMSindel#11]
I got a result like this:
INS	Hete	chr1	35850	35850	99	TATAAGTGATTTAAATATATTAAAAATCTATAAGTACATATATTTTTAATATATTTA-----AATCTATAAGTGATTTAAATATATTAAAAATATATGT	8	723	INS_ULI_8_35850	35850	High,Lowfreq

My results often contain five hyphens in the column "indel_str". Please tell me the meaning?

Thanks

**Comment by holrock** [comment]
The hyphens mean that the more longer insertion can be included, because we cannot detect distinct insertion due to a few short supported reads.
