### ISSUE TITLE
Unable to figure out code segments responsible for "De Novo Assembly"

### ISSUE THREAD

**Issue by amansinha-sw** [NCGG-MGC/IMSindel#15]
I am trying to understand the whole algorithm for this project. But I have not been able to find the "De Novo assembly of unmapped reads" code segments. Please help me with the details.

**Comment by holrock** [comment]
Hi, IMSindel don't perform De novo assembly.
Consensus sequence is made from unmapped reads using mafft.

**Comment by amansinha-sw** [comment]
I was referring the publication below:
Shigemizu, D., Miya, F., Akiyama, S. et al. IMSindel: An accurate intermediate-size indel detection tool incorporating de novo assembly and gapped global-local alignment with split read analysis. Sci Rep 8, 5608 (2018). https://doi.org/10.1038/s41598-018-23978-z
And it was unclear where exactly you were using the "De Novo Assembly".
Thanks for clarifying.
