### ISSUE TITLE
what does clip_sttpos mean?

### ISSUE THREAD

**Issue by zhangjianruwang** [NCGG-MGC/IMSindel#2]
Thank you for your reply, I have got the output of imsindel as following lines.

>indel_type     call_type       chr     sttpos  endpos  indel_length    indel_str       #indel_depth    #ttl_depth      details(indelcall_indeltype_depth)      clip_sttpos     depth(>=10)
INS     Hete    chr19   261528  261528  1       A       5       13      INS_SID_5_261528        261528  High
DEL     Homo    chr19   348405  348405  1       A       8       10      DEL_SID_8_348404        348404  High
INS     Homo    chr19   349641  349641  1       C       16      18      INS_SID_16_349641       349641  High

I do not understand the clip_sttpos. What does it mean? clipping-start position?
What is the difference between clip_sttpos and sttpos? it seems that clip_sttpos+1=sttpos.

**Comment by zhangjianruwang** [comment]
And what is the cleavage between heter and homo? 20-80?

**Comment by holrock** [comment]
As we updated our documents, please see the README file.
