### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by sbaheti84** [NCGG-MGC/IMSindel#23]
Hi,

I am trying to use the tool but getting this error. Could you please help with this error

Thanks ! Saurabh

/research/bsi/tools/biotools/imsindel/1.0.2/bin/imsindel  --bam $bam --chr chr1 --outd $PWD --indelsize 10000 --reffa $REF_GENOME 
/imsindel/1.0.2/lib/ims_indel/read_collector.rb:1:in `require_relative': 
/imsindel/1.0.2/lib/ims_indel/sam_reader.rb:16: syntax error, unexpected ',' (SyntaxError)
    def each(chr:, filter_flag: nil, output_flag: nil, &block)
                  ^
/imsindel/1.0.2/lib/ims_indel/sam_reader.rb:16: Can't assign to nil
    def each(chr:, filter_flag: nil, output_flag: nil, &block)
                                    ^
/imsindel/1.0.2/lib/ims_indel/sam_reader.rb:16: Can't assign to nil
    def each(chr:, filter_flag: nil, output_flag: nil, &block)
                                                      ^
/imsindel/1.0.2/lib/ims_indel/sam_reader.rb:29: syntax error, unexpected keyword_end, expecting end-of-input
	from /imsindel/1.0.2/lib/ims_indel/read_collector.rb:1:in `<top (required)>'
	from /imsindel/1.0.2/lib/ims_indel.rb:1:in `require_relative'
	from /imsindel/1.0.2/lib/ims_indel.rb:1:in `<top (required)>'
	from /imsindel/1.0.2/bin/imsindel:41:in `require_relative'
	from /imsindel/1.0.2/bin/imsindel:41:in `<main>'

**Comment by holrock** [comment]
Hello, what is your ruby's version?
IMSindel requires ruby 2.3 higher.

**Comment by sbaheti84** [comment]
Thanks for quick reply..

yes i am using ruby v2.6.0 

I passed the error above but now got another error


/imsindel/1.0.2/bin/imsindel --bam $bam --chr chr21 --outd $PWD --indelsize 10000 --reffa $REF_GENOME --glsearch /fasta36-36.3.8/bin/glsearch36
Traceback (most recent call last):
	6: from /imsindel/1.0.2/bin/imsindel:41:in `<main>'
	5: from /imsindel/1.0.2/bin/imsindel:41:in `require_relative'
	4: from /imsindel/1.0.2/lib/ims_indel.rb:3:in `<top (required)>'
	3: from /imsindel/1.0.2/lib/ims_indel.rb:3:in `require_relative'
	2: from /imsindel/1.0.2/lib/ims_indel/consensus.rb:1:in `<top (required)>'
	1: from /imsindel/1.0.2/miniconda3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/imsindel/1.0.2/miniconda3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bio (LoadError)

Thanks !

**Comment by holrock** [comment]
Hi,
It seems that the BioRuby is not installed.

**Comment by sbaheti84** [comment]
It worked, thanks for your help.

while running a sample through there is another error, could you please take a look at it and guide me to fix the issue. Thanks a lot !


>1. collecting indel related reads...
samtools view -F 1024 -f 2 bam chr21
#backward_clips:	29129
#forward_clips:	24793
#non_clips:	298928
>1. collecting indel related reads...done
>2. collecting unmapped reads...
samtools view -F 1024 -f 8 bam chr21
mate_unmapped_read_names: 9606
samtools view -F 1024 -f 4 bam chr21
Insert size
Avg:	292.11450799417787
SD:	22.826816261412272
#unmapped reads:	48269
>2. collecting unmapped reads...done
>3. considering support reads...
#backward clip with support reads:	1392
#forward clip with support reads:	1031
#non_clips with suport reads:	15636
>3. considering support reads...done
>4. making consensus seqs from support reads...
#backward clip with consensus:	1392 --> 1214
#forward clip with consensus:	1031 --> 873
#shot indel with consensus:	15636 --> 11227
>4. making consensus seqs from support reads...done
>5. making consensus seq from B and F..
making consensus seq for long deletion...done
>6. detection of indels...
#paired long indel candidates:	178
#unpaired long indel candidates:	905
#short indel candidates:	11227
***** ERROR [comp_lib9.c:644] cannot open library tmp/gls_seq20220216-66856-fqixkxx
command exec error: pid 38436 exit 1**
check result and inputs of the following command
bin/glsearch36 -s data/mydna.mat -g0 -f20 tmp/gls_seq20220216-66856-fqixkx tmp/gls_ref20220216-66856-eb4c1i

i ran the command above and it still complains about the file, for some reason glsearch command is adding an extra 'x' to the file and complaining.

**Comment by holrock** [comment]
It may be a bug in fasta.
Can you try with another version of fasta?

**Comment by sbaheti84** [comment]
thanks for your input, i tried different version of fasta but no luck. which version of the tool you using for the tool.

**Comment by holrock** [comment]
umm...
I using version 36.3.3d.

**Comment by sbaheti84** [comment]
I tried multiple versions of the fasta tool, from my evaluation if I supply the path to the temp folder then it fails otherwise it runs fine.

**Comment by holrock** [comment]
Thank you for reporting.  we will check this problem.
