### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by shaka-emperor** [NCGG-MGC/IMSindel#24]
Hi, I got this error with no output and don't know why... Could you please help me?

Many thanks! 

 /home/IFNgroup/yejianyu/IMSindel/bin/imsindel --thread 30 --chr chr1 --bam ../../P1_NORM_GRCh38_HBV.sort.bam --outd P1_Norm --indelsize 10000 --reffa /home/IFNgroup/yejianyu/ref/bwa_build_index/GRCh38.fa

>1. collecting indel related reads...
samtools view -F 1024 -f 2 ../../P1_NORM_GRCh38_HBV.sort.bam chr1
#backward_clips:        318998
#forward_clips: 317055
#non_clips:     1254149
>1. collecting indel related reads...done
>2. collecting unmapped reads...
samtools view -F 1024 -f 8 ../../P1_NORM_GRCh38_HBV.sort.bam chr1
mate_unmapped_read_names: 37624
samtools view -F 1024 -f 4 ../../P1_NORM_GRCh38_HBV.sort.bam chr1
Insert size
Avg:    297.33912158498964
SD:     70.2798480170345
#unmapped reads:        42986
>2. collecting unmapped reads...done
>3. considering support reads...
#backward clip with support reads:      12110
#forward clip with support reads:       7423
#non_clips with suport reads:   92888
>3. considering support reads...done
>4. making consensus seqs from support reads...
#backward clip with consensus:  12110 --> 4772
#forward clip with consensus:   7423 --> 3677
#shot indel with consensus:     92888 --> 50280
>4. making consensus seqs from support reads...done
>5. making consensus seq from B and F..
making consensus seq for long deletion...done
>6. detection of indels...
#paired long indel candidates:  335
#unpaired long indel candidates:        2688
#short indel candidates:        50280
#all_pos: 45676
#fin_indels: 45335
samtools view -F 1024 -f 2 ../../P1_NORM_GRCh38_HBV.sort.bam chr1
#all_pos_depth 45676
Traceback (most recent call last):
        7: from /home/IFNgroup/yejianyu/IMSindel/bin/imsindel:44:in `<main>'
        6: from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel.rb:52:in `run'
        5: from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel.rb:126:in `run_detect_indels'
        4: from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/indel_detector.rb:29:in `indel_call'
        3: from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/indel_detector.rb:321:in `final_indel_call'
        2: from /home/yejianyu/anaconda3/lib/ruby/2.6.0/open-uri.rb:37:in `open'
        1: from /home/yejianyu/anaconda3/lib/ruby/2.6.0/open-uri.rb:37:in `open'

**Comment by holrock** [comment]
Hi,
could you check that P1_Norm directory exists?

**Comment by shaka-emperor** [comment]
Thanks a lot!
And sorry to bother you again. My bam file has 32.5GB (average human WGS size), 5 threads, and detection of chromosome1 took me around 2.5 days. If I want to test all 24 chromosomes in one sample, it may cost one month... Is there any suggestions to accelerate the process? I like this software for its easy-to-use

**Comment by holrock** [comment]
`--temp /dev/shm` option runs faster than default option.

Unfortunately,  IMSindel is slow.
we use PC cluster for analysis.

**Comment by shaka-emperor** [comment]
Many thanks~
