### ISSUE TITLE
Convert output to VCF / get reference allele

### ISSUE THREAD

**Issue by thedam** [NCGG-MGC/IMSindel#3]
Hi,
I'd like to convert IMSindel output to VCF-like format.
VCF contains fields:
`chr, start_pos, whateverID, ref_allel, alt_allel`
and IMSindel only gives:
`chr, sttpos, indel_str`

How to determine `ref_allel`? 

is it enough to make a trick:
`samtools faidx ref.fa chr:sttpos-sttpos`
`samtools faidx ref.fa 1:13657-13657`
or maybe you could modify the code to output this :) 

Thanks for advice!:)
Damian

**Comment by holrock** [comment]
We are planning VCF support in a future release.
Please use that workaround now.
Thanks!
