### ISSUE TITLE
warning: Insecure world writable dir

### ISSUE THREAD

**Issue by thedam** [NCGG-MGC/IMSindel#5]
Hi,
I report some warning. Probably it's not important, however I'd feel better to know what does it mean:
```
samtools:       samtools
temp:   /tmp
thread: 1
exclude-region: 

>1. collecting indel related reads...
samtools view -F 1024 -f 2 /mnt/ssd_01/production/S400_1/54951AM/54951AM.bam X
/mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel/sam_reader.rb:22: warning: Insecure world writable dir /mnt/ssd_01 in PATH, mode 040777
```

Cheers

**Comment by holrock** [comment]
Hi, thanks for the report.
That warning occurs to directory permission (https://stackoverflow.com/questions/32325413/warning-insecure-world-writable-dir-usr-in-path-mode-040777)
Please set permissoin 755 to /mnt/ssd_01 if you can (or ignore that)

**Comment by thedam** [comment]
This one I can't, but subdirs of this dir have full read/write permissions.
Ok thanks.
