### ISSUE TITLE
fasta36 download link changed

### ISSUE THREAD

**Issue by mschroed** [NCGG-MGC/IMSindel#9]
Just FYI,

the filename for the current release of fasta has the t missing in fasta:
http://faculty.virginia.edu/wrpearson/fasta/CURRENT/fasa36-linux64.tar.gz

Your Dockerfile breaks by pointing to:
curl -OL http://faculty.virginia.edu/wrpearson/fasta/CURRENT/fasta36-linux64.tar.gz

**Comment by holrock** [comment]
Thank you for information!
We fixed fasta URL.
